name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Super-Linter
        uses: github/super-linter@v4.8.1
        env:
          VALIDATE_ALL_CODEBASE: True
          DEFAULT_BRANCH: main
          LOG_LEVEL: WARN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
